INSERT INTO bank (name, nationality, residence) VALUES ('Komereční banka','Česká republika','Brno');
INSERT INTO bank (name, nationality, residence) VALUES ('Česká spořitelna','Česká republika','Praha');
INSERT INTO bank (name, nationality, residence) VALUES ('ČSOB','Česká republika','Olomouc');
INSERT INTO bank (name, nationality, residence) VALUES ('mBANK','Česká republika','Jihlava');
INSERT INTO bank (name, nationality, residence) VALUES ('Equa Bank','Česká republika','Praha');
INSERT INTO bank (name, nationality, residence) VALUES ('Air Bank','Česká republika','Uherské Hradiště');

INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.001,TRUE, FALSE, FALSE, FALSE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.005,TRUE, TRUE, FALSE, FALSE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.007,TRUE, TRUE, TRUE, FALSE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.007,TRUE, FALSE, TRUE, TRUE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.007,TRUE, TRUE, FALSE, TRUE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.007,TRUE, FALSE, FALSE, TRUE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.008,TRUE, FALSE, TRUE, FALSE);
INSERT INTO insurance (extra_price, theft, accident, rubbing, lost_keys) VALUES (0.13,TRUE, TRUE, TRUE, TRUE);

INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Suzuki', 'Swift Sport', 2020, 'yellow', 5, 'Toyota', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Toyota', 'Supra', 2000, 'black', 2, 'Toyota', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Audi', 'TT', 2021, 'blue', 2, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Audi', 'RS6', 2019, 'grey', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Škoda', 'Octavia RS', 2021, 'green', 5, 'VW Group', 'Czech republic');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Golf GTI', 2021, 'white', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Golf R', 2021, 'blue', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Passat', 2019, 'silver', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Arteon', 2020, 'yellow', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Golf Variant', 2018, 'black', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Passat', 2000, 'blue', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Golf', 2003, 'silver', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Bora', 2001, 'silver', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Jetta', 1995, 'black', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'T-Roc', 2019, 'blue', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Polo', 2020, 'red', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'T-Cross', 2021, 'black', 5, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Volkswagen', 'Multivan', 2021, 'blue', 7, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Nissan', 'Skyline R33', 1995, 'white', 2, 'Nissan', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Nissan', 'Skyline R34', 2000, 'blue', 2, 'Nissan', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Bentley', 'Continental GT', 2018, 'grey', 2, 'VW Group', 'UK');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Rolls-Royce', 'Ghost', 2020, 'white', 4, 'BMW', 'UK');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e36)', 1992, 'silver', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e36)', 1997, 'green', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e46)', 2001, 'black', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e46)', 2000, 'white', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (e46)', 2002, 'black', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (e36)', 1995, 'white', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '5 (e34)', 1992, 'white', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '5 (e39)', 2000, 'blue', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M5 (e39)', 2000, 'blue', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e92)', 2007, 'white', 4, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (e92)', 2006, 'purple', 4, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (e91)', 2006, 'grey', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', '3 (f80)', 2016, 'purple', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (f80)', 2017, 'khaki', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (f80)', 2018, 'green', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (g80)', 2020, 'green', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M3 (g80)', 2021, 'blue', 5, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M4 (g82)', 2021, 'yellow', 4, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('BMW', 'M4 (g82)', 2021, 'white', 4, 'BMW', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Mercedes-Benz', 'E Klasse', 2003, 'silver', 5, 'Mercedes-Benz', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Mercedes-Benz', 'C Klasse', 2002, 'silver', 5, 'Mercedes-Benz', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Škoda', 'Octavia Combi', 2020, 'silver', 5, 'VW Group', 'Czech republic');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Škoda', 'Octavia', 2021, 'blue', 5, 'VW Group', 'Czech republic');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Škoda', 'Octavia', 2021, 'red', 5, 'VW Group', 'Czech republic');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Škoda', 'Octavia Combi', 2021, 'black', 5, 'VW Group', 'Czech republic');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Honda', 'Civic', 1992, 'blue', 5, 'Honda', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Honda', 'Civic', 2000, 'silver', 5, 'Honda', 'Japan');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Porsche', '911 GT3 RS', 2021, 'yellow', 2, 'VW Group', 'Germany');
INSERT INTO brand (name, model, year, color, capacity, concern, country) VALUES ('Porsche', '911 Turbo S', 2020, 'orange', 2, 'VW Group', 'Germany');

INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (2,'fabric', FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,TRUE, TRUE);
INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (4,'fabric', FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,TRUE, TRUE);
INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (2,'leather', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,TRUE, TRUE);
INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (4,'leather', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,TRUE, TRUE);
INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (2,'fabric', FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE);
INSERT INTO equipment (number_of_doors, interior_material, has_automatic_transmition, has_ABS, has_EDS, has_parking_assistent, has_tempomat, has_parking_sensors, has_airbags, has_power_steering_wheel, has_air_conditioning, has_tuning, has_usb) VALUES (4,'fabric', FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE);

INSERT INTO tuning (mm_lowering, has_sport_intake, has_sport_seats, has_modified_exhaust, has_ceramic_clutch, has_hydro_handbrake, has_sport_suspention, has_wheel_spacers) VALUES (20, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE);
INSERT INTO tuning (mm_lowering, has_sport_intake, has_sport_seats, has_modified_exhaust, has_ceramic_clutch, has_hydro_handbrake, has_sport_suspention, has_wheel_spacers) VALUES (30, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE);
INSERT INTO tuning (mm_lowering, has_sport_intake, has_sport_seats, has_modified_exhaust, has_ceramic_clutch, has_hydro_handbrake, has_sport_suspention, has_wheel_spacers) VALUES (20, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE);
INSERT INTO tuning (mm_lowering, has_sport_intake, has_sport_seats, has_modified_exhaust, has_ceramic_clutch, has_hydro_handbrake, has_sport_suspention, has_wheel_spacers) VALUES (0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE);
INSERT INTO tuning (mm_lowering, has_sport_intake, has_sport_seats, has_modified_exhaust, has_ceramic_clutch, has_hydro_handbrake, has_sport_suspention, has_wheel_spacers) VALUES (30, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);

INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo, name) VALUES (1373, 103, 230, FALSE, TRUE, 'ZC33S');
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo, name) VALUES (2997, 243, 441, FALSE, TRUE, '2JZ-GTE');
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1498, 110, 250, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo, name) VALUES (1896, 96, 310, FALSE, TRUE, 'ASZ');
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3996, 441, 800, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1968, 169, 350, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1984, 221, 400, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1984, 235, 420, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo, name) VALUES (2568, 350, 501, FALSE, TRUE, 'RB26DETT');
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (5950, 467, 900, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (6593, 420, 820, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1785, 81, 150, FALSE, FALSE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2496, 141, 211, FALSE, FALSE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3198, 221, 350, FALSE, FALSE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2993, 353, 550, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2148, 110, 300, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1386, 86, 163, FALSE, FALSE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3996, 383, 470, FALSE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 427, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3000, 180, 500, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (5990, 400, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (4990, 285, 480, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2500, 170, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2500, 180, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2500, 190, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 427, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3500, 390, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1900, 110, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 427, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2800, 195, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2800, 195, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 420, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 427, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3500, 290, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 390, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3000, 300, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2700, 285, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3900, 410, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (6000, 520, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3400, 300, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2700, 240, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3800, 425, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3000, 250, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1900, 110, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (2900, 170, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (3000, 180, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1900, 110, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1600, 74, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (1900, 96, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (5990, 620, 700, TRUE, TRUE);
INSERT INTO engine (ccm_volume, kW_performance, Nm_torque, has_four_wheel_drive, has_turbo) VALUES (5990, 520, 700, TRUE, TRUE);

INSERT INTO credential (ID_card_id, driving_licence_id, passport_id) VALUES (205865645, 653125123, 98124124);
INSERT INTO credential (ID_card_id, driving_licence_id, passport_id) VALUES (205569663, 125124123, 7124125);
INSERT INTO credential (ID_card_id, driving_licence_id, passport_id) VALUES (203868555, 7124984, 5124125);
INSERT INTO credential (ID_card_id, driving_licence_id) VALUES (719231, 61299421);
INSERT INTO credential (ID_card_id, driving_licence_id) VALUES (202663656, 31268392);
INSERT INTO credential (ID_card_id, driving_licence_id) VALUES (201162464, 44327493);

INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 1);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 2);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'coupe', 12000, FALSE, 4, 3);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'combi', 12000, FALSE, 4, 4);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'liftback', 12000, FALSE, 4, 5);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 6);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 7);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 3, 8);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 9);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'combi', 12000, FALSE, 4, 10);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 11);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 12);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 13);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 14);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'SUV', 12000, FALSE, 4, 15);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 16);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'SUV', 12000, FALSE, 4, 17);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'combi', 12000, FALSE, 4, 18);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 19);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 1);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 2);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 1, 3);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 4);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 5);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 6);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 7);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 5, 8);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 2, 9);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 9);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 10);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 11);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 12);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 2, 13);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 14);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 15);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 16);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 17);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 18);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 19);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 10);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 11);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 12);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'sedan', 12000, FALSE, 4, 13);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'combi', 12000, FALSE, 4, 14);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'liftback', 12000, FALSE, 4, 15);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'liftback', 12000, FALSE, 4, 16);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'combi', 12000, FALSE, 4, 17);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 18);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'hatchback', 12000, FALSE, 4, 19);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'coupe', 12000, FALSE, 2, 10);
INSERT INTO status (fuel, bodywork, mileage, has_winter_tyres, tuning_id, engine_id) VALUES ('100%', 'coupe', 12000, FALSE, 3, 11);

INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0000', '100', TRUE, 1, 1, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0001', '100', TRUE, 2, 2, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0002', '100', TRUE, 3, 3, 3);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0003', '100', TRUE, 4, 4, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0004', '100', TRUE, 5, 5, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0005', '100', TRUE, 6, 6, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0006', '100', TRUE, 7, 7, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0007', '100', FALSE, 8, 8, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0008', '100', TRUE, 9, 9, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0009', '100', TRUE, 10, 10, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0010', '100', TRUE, 11, 11, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0011', '100', TRUE, 12, 12, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0012', '100', TRUE, 13, 13, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0013', '100', TRUE, 14, 14, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0014', '100', TRUE, 15, 15, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0015', '100', TRUE, 16, 16, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0016', '100', TRUE, 17, 17, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0017', '100', TRUE, 18, 18, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0018', '100', TRUE, 19, 19, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0019', '100', TRUE, 20, 20, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0020', '100', TRUE, 21, 21, 3);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0021', '100', TRUE, 22, 22, 3);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0022', '100', TRUE, 23, 23, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0023', '100', TRUE, 24, 24, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0024', '100', TRUE, 25, 25, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0025', '100', TRUE, 26, 26, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0026', '100', TRUE, 27, 27, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0027', '100', TRUE, 28, 28, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0028', '100', TRUE, 29, 29, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0029', '100', TRUE, 30, 30, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0030', '100', TRUE, 31, 31, 6);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0031', '100', TRUE, 32, 32, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0032', '100', TRUE, 33, 33, 1);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0033', '100', TRUE, 34, 34, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0034', '100', TRUE, 35, 35, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0035', '100', TRUE, 36, 36, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0036', '100', TRUE, 37, 37, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0037', '100', TRUE, 38, 38, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0038', '100', TRUE, 39, 39, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0039', '100', TRUE, 40, 40, 1);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0040', '100', TRUE, 41, 41, 1);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0041', '100', TRUE, 42, 42, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0042', '100', TRUE, 43, 43, 3);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0043', '100', TRUE, 44, 44, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0044', '100', FALSE, 45, 45, 2);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0045', '100', FALSE, 46, 46, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0046', '100', TRUE, 47, 47, 4);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0047', '100', TRUE, 48, 48, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0048', '100', TRUE, 49, 49, 5);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0049', '100', TRUE, 50, 50, 3);
INSERT INTO car (licence_plate, tank_condition, is_available, status_id, brand_id, equipment_id) VALUES ('3BA0050', '100', TRUE, 51, 51, 3);

INSERT INTO name (first_name, last_name) VALUES ('Matěj', 'Hrabálek');
INSERT INTO name (first_name, last_name) VALUES ('Vladimír', 'Dušek');
INSERT INTO name (first_name, last_name) VALUES ('Tomáš', 'Nejeschleba');
INSERT INTO name (first_name, last_name) VALUES ('Libor', 'Petrucha');
INSERT INTO name (title_before_name, first_name, last_name) VALUES ('Mgr.', 'Martin', 'Hrášek');
INSERT INTO name (title_before_name, first_name, last_name) VALUES ('Bc.', 'Evžen', 'Polášek');
INSERT INTO name (first_name, last_name) VALUES ('Michal', 'Hnátek');
INSERT INTO name (title_before_name, first_name, last_name) VALUES ('Ing.', 'Lubomír', 'Chludil');
INSERT INTO name (first_name, last_name) VALUES ('Tomáš', 'Němec');
INSERT INTO name (title_before_name, first_name, last_name) VALUES ('Mgr.', 'Petr', 'Svoboda');
INSERT INTO name (first_name, last_name) VALUES ('Lukáš', 'Beneš');

INSERT INTO contact (phone_number, email) VALUES (765659731, 'matejhrabalek@mail.com');
INSERT INTO contact (phone_number, email) VALUES (758655639, 'vladimirdusek@mail.com');
INSERT INTO contact (phone_number, email) VALUES (605855771, 'tomasnejeschleba@mail.com');
INSERT INTO contact (phone_number, email) VALUES (869675456, 'liborpetrucha@mail.com');
INSERT INTO contact (phone_number, email) VALUES (775654538, 'martinhrasek@mail.com');
INSERT INTO contact (phone_number, email) VALUES (745654526, 'evzenpolasek@mail.com');
INSERT INTO contact (phone_number, email) VALUES (756684552, 'michalhnatek@mail.com');
INSERT INTO contact (phone_number, email) VALUES (712350500, 'lubachludil@mail.com');
INSERT INTO contact (phone_number, email) VALUES (712350500, 'tomnemec@mail.com');
INSERT INTO contact (phone_number, email) VALUES (712350500, 'petrsvoboda@mail.com');
INSERT INTO contact (phone_number, email) VALUES (712350500, 'lukasnemec@mail.com');

INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Uherský Brod', 'Brodská', '98', '98673', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Uherský Ostroh', 'Blatnická', '1', '45623', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Polešovice', 'Na dědině', '1007', '42687', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Brno', 'Polní', '105', '42635', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Jihlava', 'Vyvýšená', '2', '12356', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Traplice', 'Babická', '81', '69236', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Blatnice pod Svatým Antonínkem', 'Veselská', '185', '69811', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Kunovice', 'Na Řádku', '662', '69321', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Uherké Hradiště', 'Sady', '33', '69569', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Staré Město', 'Staroměstská', '778', '695698', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Vracov', 'Zahradská', '1302', '69803', FALSE, TRUE);
INSERT INTO address (city, street, house_number, zip_code, is_our_workplace, is_customers_address) VALUES ('Brno', 'Technická', '12', '69601', TRUE, FALSE);

INSERT INTO employee (wage, employed_since, place_of_employment, name_id, contact_id, address_id) VALUES (0.03, '2021-01-05', 'Brno', 7, 7, 7);
INSERT INTO employee (wage, employed_since, place_of_employment, name_id, contact_id, address_id) VALUES (0.02, '2021-08-01', 'Brno', 8, 8, 8);
INSERT INTO employee (wage, employed_since, place_of_employment, name_id, contact_id, address_id) VALUES (0.014, '2021-05-06', 'Brno', 9, 9, 9);
INSERT INTO employee (wage, employed_since, place_of_employment, name_id, contact_id, address_id) VALUES (0.015, '2021-04-24', 'Brno', 10, 10, 10);
INSERT INTO employee (wage, employed_since, place_of_employment, name_id, contact_id, address_id) VALUES (0.01, '2021-10-22', 'Brno', 11, 11, 11);

INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('1998-02-04', 'Czech', 1, 1, 1, 1);
INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('1988-11-11', 'Czech', 2, 2, 2, 2);
INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('1956-06-30', 'Czech', 3, 3, 3, 3);
INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('1993-02-25', 'Czech', 4, 4, 4, 4);
INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('2001-05-14', 'Czech', 5, 5, 5, 5);
INSERT INTO customer (date_of_birth, nationality, address_id, credential_id, contact_id, name_id) VALUES ('1974-09-01', 'Czech', 6, 6, 6, 6);

INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (1, 1, '4568456845682354');
INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (2, 2, '5698756912254265');
INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (3, 3, '4523456891220015');
INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (4, 4, '4265023444220098');
INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (5, 5, '4268453654104206');
INSERT INTO customer_has_bank (customer_id, bank_id, credit_card_number) VALUES (6, 6, '1235024251440256');

INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (0.01,'2021-10-22', '2021-12-30', 1, 12, 1, 3, 3);
INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (0.09,'2021-11-22', '2021-12-26', 2, 12, 2, 20, 6);
INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (0.1,'2021-11-22', '2022-02-21', 3, 12, 2, 27, 4);
INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (2,'2021-11-03', '2022-06-03', 4, 12, 3, 50, 8);
INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (2.1,'2021-11-11', '2022-06-11', 5, 12, 4, 51, 8);
INSERT INTO rent (price_of_rent, date_of_pickup, date_of_return, customer_id, pickup_address_id, employee_id, car_id, insurance_id) VALUES (0.005,'2021-12-02', '2021-12-30', 6, 12, 5, 42, 1);
